import { Band } from './band.model';

export const BANDS: Band[] = [
  {
    id: 1,
    name: 'Khruangbin',
    genre: 'Psychedelic Rock',
    activeSince: 2010,
    newCol: '',
    state: 'Active',
  },
  {
    id: 2,
    name: 'Kyuss',
    genre: 'Desert Rock',
    activeSince: 1987,
    newCol: '',
    state: 'Active',
  },
  {
    id: 3,
    name: 'Bolt Thrower',
    genre: 'Death Metal',
    activeSince: 1986,
    newCol: '',
    state: 'Split Up',
  },
  {
    id: 4,
    name: 'GOLD',
    genre: 'Dark Rock',
    activeSince: 2011,
    newCol: '',
    state: 'Active',
  },
  {
    id: 5,
    name: 'Roger Alan Wade',
    genre: 'Country',
    activeSince: 2005,
    newCol: '',
    state: 'Active',
  },
  {
    id: 6,
    name: 'Mgla',
    genre: 'Black Metal',
    activeSince: 2000,
    newCol: '',
    state: 'Active',
  },
  {
    id: 7,
    name: 'Esperanza Spalding',
    genre: 'Jazz',
    activeSince: 2000,
    newCol: '',
    state: 'Active',
  },
  {
    id: 8,
    name: 'Failure',
    genre: 'Alternative Rock',
    activeSince: 1990,
    newCol: '',
    state: 'Active',
  },
  {
    id: 9,
    name: 'The Arson Project',
    genre: 'Grindcore',
    activeSince: 2005,
    newCol: '',
    state: 'Active',
  },
  {
    id: 10,
    name: 'Death In June',
    genre: 'Neofolk',
    activeSince: 1981,
    newCol: '',
    state: 'Active',
  },
];
